apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - cd /code/server && ls && ./entrypoint.sh
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DJANGO_SECRET_KEY
              value: do_not_use_in_production
            - name: HAMILTON_AUTH_MODE
              value: permissive
            - name: HAMILTON_BLOB_STORE
              value: local
            - name: HAMILTON_ENV
              value: local
            - name: HAMILTON_LOCAL_BLOB_DIR
              value: /data/blobs
            - name: HAMILTON_TELEMETRY_ENABLED
              value: "true"
          image: dagworks/ui-backend:latest
          name: backend
          ports:
            - containerPort: 8241
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: backend-data
      restartPolicy: Always
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-data
