# Generated by Django 4.2.4 on 2023-10-10 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trackingserver_projects", "0001_initial"),
        ("trackingserver_template", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dagtemplate",
            unique_together={("dag_hash", "code_hash", "name", "project")},
        ),
    ]
